# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login
      uses: actions/heroku@main
      evn:
          HEROKU_API_KEY : ${{secrets.$HEROKU_API_KEY}}
      with:
        args: container:login
    - name: push
      uses: action/heroku@main
      env :
           HEROKU_API_KEY : ${{secrets.$HEROKU_API_KEY}}
      with :
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          usedocker: true
